rvm:
  - "2.2.1"
env: 
  - "RAILS_ENV=test DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=3"
services:
  - redis-server
before_install:
  # INSTALL MYSQL 5.6
  # (https://github.com/piwik/piwik/commit/20bd2e1c24e5d673dce3feb256204ad48c29f160)
  # TODO: Remove when mysql 5.6 is provided by travis.
  # Otherwise, our migrations will raise a syntax error.
  - "sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5"
  - "sudo apt-get autoremove"
  - "sudo apt-get install libaio1"
  - "wget -O mysql-5.6.14.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.14-debian6.0-x86_64.deb/from/http://cdn.mysql.com/"
  - "sudo dpkg -i mysql-5.6.14.deb"
  - "sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql.server"
  - "sudo ln -s /opt/mysql/server-5.6/bin/* /usr/bin/"
  - "sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf"
  - "sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf"
  - "sudo sed -i'' 's/basedir[^=]\\+=.*$/basedir = \\/opt\\/mysql\\/server-5.6/' /etc/mysql/my.cnf"
  - "sudo /etc/init.d/mysql.server start"
  - mysql --version
  - mysql -e "SELECT VERSION();"
  # /END MYSQL 5.6
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - sudo apt-get -y install pwgen libicu-dev
  - travis_retry bundle install
before_script:
  - cd demo_app/my_platform
  - cp config/database.travis.yml config/database.yml
  - mkdir -p public/uploads
  - mkdir -p tmp/cache
  - bundle exec rake db:create db:migrate
  - cd ../..
script:
  - bundle exec rake rspec-rerun:spec
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/14aec2cb97b9e0f2a808
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
